### PR TITLE
WIP: 0.8.8 develop branch

### PR DESCRIPTION
**Pull request by jgriffiths**
Tracking all post 0.8.7 changes here for a while in case 0.8.7 needs a patch release.

### CODE REVIEW

**Comment by JamieDriver** [comment]
Not changed in this MR, but a quick fix (taking liberties, I know!) :
`wally_map_init()` and 
`wally_map_init_alloc()` documentation (`wally_map.h`) does not include `wally_map_verify_fn_t verify_fn`.

**Comment by jgriffiths** [comment]
> Not changed in this MR,

@JamieDriver fixed, thanks for the report.

**Comment by JamieDriver** [comment]
I've been using this branch for the past few weeks in Jade development, keeping up to date with branch updates.  
All working well for me - my main focus has been on using the new PSBT-related functions and these all seem to be good.  Not seen any regressions of any sort in general wally use.  
So as far as I am concerned, ack c1f1ddbe

**Comment by jgriffiths** [comment]
thanks @JamieDriver I'm just waiting for some final JS updates from @shesek in this branch and will merge it after that, cheers.

**Pull request merged**
