### PR TITLE
Issue 178 - don't override CFLAGS, default to O2

### PR DESCRIPTION
**Pull request by greenaddress**

### CODE REVIEW

**Comment by jkauffman1** [comment]
utack 0d06449080645af34a8b6c8cd620c4b848b7e5b9

**Comment by NickeZ** [comment]
nack

```
$ CFLAGS="-Os" ../configure
...
  CFLAGS                  = -Os -W -std=c89 -pedantic -Wall -Wextra -Wcast-align -Wnested-externs -Wshadow -Wstrict-prototypes -Wno-unused-function -Wno-long-long -Wno-overlength-strings -fvisibility=hidden -O2
  CPPFLAGS                =
  LDFLAGS                 =  -O2 -Wl,-z,relro
```

It still looks like `-O2` is added at the end, which will override `-Os`.

**Comment by greenaddress** [comment]
@NickeZ fair enough & good catch 

Better now?

**Comment by NickeZ** [comment]
tACK, seems correct.

**Comment by greenaddress** [comment]
for reference  https://github.com/bitcoin-core/secp256k1/pull/700#issuecomment-591134784

**Pull request merged**
