### PR TITLE
Sighash rangeproof

### PR DESCRIPTION
**Pull request by jgriffiths**
Merge branch for rangeproof sighash support from @k-matsuzawa (see https://github.com/ElementsProject/libwally-core/pull/270)

### CODE REVIEW

**Comment by LeoComandini** [comment]
utACK 47462d0ab64fb7007607ecafc367f875eefddf46, are we adding tests later?

**Comment by jgriffiths** [comment]
> utACK [47462d0](https://github.com/ElementsProject/libwally-core/commit/47462d0ab64fb7007607ecafc367f875eefddf46), are we adding tests later?

I'll squash this so  @k-matsuzawa has a commit to use in his tree, and see if I can get time to add some tests before merging.

**Comment by shats15** [comment]
- # enforce correct line endings for shell and batch files.*.sh text eol=lfscript/* text eol=lfscript/*.bat text eol=crlf

© 2021

**Comment by shats15** [comment]
# enforce correct line endings for shell and batch files.*.sh text eol=lfscript/* text eol=lfscript/*.bat text eol=crlf

© 2021 
https://github.com/ryo-ma/deno-websocket#readme

**Pull request merged**
