### PR TITLE
Further ABI updates

### PR DESCRIPTION
**Pull request by jgriffiths**
Expose alloc functions and set the DSO version.

### CODE REVIEW

**Comment by whitslack** [comment]
@jgriffiths: `LT_VER_CURRENT` needs to start at 1 because you've already burned the `.0` soname in prior releases.

**Comment by jgriffiths** [comment]
> @jgriffiths: `LT_VER_CURRENT` needs to start at 1 because you've already burned the `.0` soname in prior releases.

Yes, I will bump it to 1 with the release of 1.0, prior to that being tagged all bets remain off!

**Comment by whitslack** [comment]
> Yes, I will bump it to 1 with the release of 1.0, prior to that being tagged all bets remain off!

Agreed. I thought you were going to merge this PR to produce the 1.0 release. I've stripped out my fixup.

**Comment by jgriffiths** [comment]
Merged under https://github.com/ElementsProject/libwally-core/pull/423, closing.

**Pull request closed without merging**
