### PR TITLE
docs: Add list of projects and products that are known to depend on or use libwally

### PR DESCRIPTION
**Pull request by practicalswift**
Add list of projects and products that are known to depend on or use `libwally`.

Am I missing any known users? :-)

### CODE REVIEW

**Comment by glslang** [comment]
utAck 471902c

**Comment by greenaddress** [comment]
utack 471902c, my only nit is that I suggest we put a little disclaimer that those projects may be experimental, superseded etc

**Comment by practicalswift** [comment]
@greenaddress Good point! I've now added a disclaimer -- please re-review.

Also: am I missing any prominent users of the library?

**Comment by greenaddress** [comment]
@practicalswift looks good to me, thank you!

I checked with a few and we think you got all prominent users of the library, cheers, will merge

**Pull request merged**
