### PR TITLE
Make emscripten emcc options configurable

### PR DESCRIPTION
**Pull request by shesek**
This also changes the default optimization level to 3 (tested to work) and renames the target directory to `wasm_dist`.

### CODE REVIEW

**Comment by shesek** [comment]
Wasn't sure which functions should get exported by default, should it be all of them?

**Comment by jgriffiths** [comment]
> Wasn't sure which functions should get exported by default, should it be all of them?
Hi @shesek, Ideally we should export all external functions, yes. A couple of comments:

- Elements support should be optional, controlled with an argument to the script like '--enable-elements'
- `--enable-export-all` should be removed from the configure arguments
- If `emcc` can take an file to list the exports rather than a command line option, it would be good to add support for generating this file via `./tools/build_wrappers.py`, alternately the script itself can be updated by `build_wrappers.py` in the same way as the other generated code (this ensures it will stay up to date going forward when new functions are added).
- It might be cleaner to pull your own branch, cherry pick Lawrences commit, add your changes and PR that, as this branch needs rebasing.
- I will see about updating our greenaddrress build images to include the wasm deps so this can me merged for the next release.

We may want to put something in README.md on safety as well, I don't know if the constant time code in secp or the AES code will remain constant time once transpiled. So users may want to avoid signing or encrypting using this build.

Cheers!

**Comment by jgriffiths** [comment]
@shesek Might be a plan to hold off for a day or two, we will merge the changes from https://github.com/ElementsProject/libwally-core/pull/248/ soon which should give us an up to date docker image base to build masm support from

**Comment by shesek** [comment]
Thanks for your review and help!

> If `emcc` can take an file to list the exports rather than a command line option, it would be good to add support for generating this file via `./tools/build_wrappers.py`, ...

The `build_wasm.sh` script could get extract the list of functions in directly from the headers to create the json array, with something like this:

`gcc -E include/*.h | sort | uniq | grep '^ *int ' | grep '(' | sed -e 's/^ *int //g' -e 's/(.*//g' | egrep '^wally_|^bip' | jq -R -s -c '[split("\n")[]|select(length>0)] | map("_"+.)'`

(Based on the code from `build_wrappers.py`, with `jq` to serialize as an array. Can we assume to have jq`` available?)

> the `client/src/lib/libwally.js` wrappers in the esplora commit look like they might be useful to provide with wally itself, particularly if they can be auto-generated. 

Yes, definitely, auto-generating wrappers to expose whole of libwally would be great. I only needed two so it was easier to just implement them manually, but I'll look into the tooling available for auto generation.

**Comment by jgriffiths** [comment]
@shesek, I'm implementing autogeneration now, please hold on for a bit and I'll push the PR after testing...

**Comment by jgriffiths** [comment]
@shesek please see https://github.com/ElementsProject/libwally-core/pull/249 which auto-generates the function lists, adds `--enable-elements` to optionally include elements support, and lets the user override the exported functions by setting `EXPORTED_FUNCTIONS` themselves.

Our CI has passed that PR, so we should be merging it shortly (after some manual testing). Please feel free to open a new PR or issue if there's something broken or anything further you need.

**Comment by shesek** [comment]
@jgriffiths Looks great! :+1:

**Pull request closed without merging**
